<?php
print "<h2> Content form ajax.php </h2>
		<div>Some info from ajax.php.
		In turpis neque, elementum id auctor vitae, semper vel ante. Donec tincidunt vestibulum metus, ut molestie orci egestas sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras lacinia tellus id nunc facilisis a luctus augue pretium. Sed suscipit dolor in turpis egestas tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consequat quam eget nisi tempus convallis! Sed lacinia molestie aliquam. Aenean lobortis accumsan tellus id dictum. Nunc eget placerat ante. Quisque vulputate orci quis lectus rhoncus volutpat. Curabitur et neque et risus tempus elementum.

Phasellus varius condimentum porta. Sed bibendum leo sed augue elementum porttitor. Ut a nisl sem. Donec tristique, lorem ac eleifend viverra; mauris massa consectetur sem, vitae lobortis sem dui a justo. Nam in ullamcorper neque. Integer non sem a leo tincidunt laoreet. Aenean bibendum nunc id sapien luctus eget tempor neque condimentum. Etiam semper nunc ac nibh scelerisque tincidunt? Mauris dapibus, tellus sed suscipit lacinia; lorem magna ullamcorper enim, nec auctor ligula orci at ipsum. Pellentesque sollicitudin elit ut augue tempor non auctor ipsum posuere. Integer feugiat lorem non quam dapibus vitae lacinia eros lacinia? Phasellus scelerisque eros id ligula accumsan sit amet porta tortor rhoncus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum eget diam nulla, quis interdum dolor. Integer eget nunc nisi, sed interdum lorem. Quisque neque dui, congue sit amet sodales nec, sagittis sit amet purus. Praesent egestas tincidunt pulvinar.

Nunc purus ligula, malesuada et condimentum eget, ullamcorper eu ligula? Sed a massa nunc, in congue nibh. Phasellus libero diam; pulvinar eget tincidunt sit amet, tincidunt sed tellus? Cras ut nisl erat. Maecenas molestie porttitor magna non interdum! Suspendisse congue dolor sit amet dolor pulvinar ut rhoncus felis tincidunt. Curabitur at augue quis elit venenatis lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed pretium nulla ac nisl imperdiet tempus sit amet congue sapien. Integer sed tortor tortor. Integer posuere ultricies enim quis egestas. Maecenas laoreet, nisl at euismod gravida, sem mi porta ante, vitae mattis nulla tellus eget sapien. Vivamus arcu est; interdum ut vulputate sit amet, dignissim at orci. Morbi molestie blandit mauris, et faucibus massa congue ac. Duis fermentum vehicula magna, a commodo arcu pharetra in. Nulla nunc lacus, bibendum eu ultricies quis, tristique ac turpis. Pellentesque a eros libero, molestie mattis magna. In sodales urna ante, eu scelerisque dui. Fusce justo leo, imperdiet nec dapibus vitae, dapibus sed lacus.
		</div>
		";

?>